language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as test
before_script:
  - echo "no test"

#  Build
script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed odili/udagram-api-feed:v1
  - docker tag udagram-api-user odili/udagram-api-user:v1
  - docker tag udagram-frontend odili/udagram-frontend:v1
  - docker tag reverseproxy odili/reverseproxy:v1

# Push to DockerHub
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push odili/udagram-api-feed
  - docker push odili/udagram-api-user
  - docker push odili/udagram-frontend
  - docker push odili/reverseproxy
