language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as test
before_script:
  - echo "no test"

#  Build and Tagging
script:
  - docker --version # print the version for logging
  - docker build -t odili/udagram-api-feed:v1 ./udagram-api-feed
  - docker build -t odili/udagram-api-user:v1 ./udagram-api-user
  - docker build -t odili/udagram-frontend:v1 ./udagram-frontend
  - docker build -t odili/reverseproxy:v1 ./udagram-reverseproxy

# Push to DockerHub
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push odili/udagram-api-feed
  - docker push odili/udagram-api-user
  - docker push odili/udagram-frontend
  - docker push odili/reverseproxy
