apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: odili/udagram-api-user
          imagePullPolicy: Always
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '2048Mi'
              cpu: '500m'
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
          volumeMounts:
            - name: aws-secret
              mountPath: /root/.aws/
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
