apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
spec:
  type: LoadBalancer
  selector:
    app: udagram-frontend
  ports:
    - name: '8100'
      protocol: TCP
      port: 8100
      targetPort: 80
